services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://mlbd:postgres@db:5432/taskhive
      MAIL_SERVER: mail
      MAIL_PORT: 1025
      ALGORITHM: HS256
      TOKEN_EXPIRE_HOURS: 1
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env # mount the .env file
    depends_on:
      - db
    networks:
      - taskhive-net

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    depends_on:
      - backend
    networks:
      - taskhive-net

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: mlbd
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskhive
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskhive-net

volumes:
  postgres_data:

networks:
  taskhive-net:
    driver: bridge
